#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

source /usr/share/git/completion/git-completion.bash
shopt -s checkwinsize

# EXPORT ENVIRONMENT VARIABLES
export EDITOR=vim

PS1='[\u@\h \W]\$ '


# CUSTOM PATH ENTRIES; SOME MAY BE OUT OF DATE
PATH=$PATH:.
PATH=$PATH:/home/jon/bin
PATH=$PATH:/home/jon/.screenlayout
PATH=$PATH:/home/jon/.gem/ruby/2.2.0/bin/

export JAVA_HOME="/usr/lib/jvm/default"

VBOX_USB=usbfs


# ALIAS COMMANDS TO EASIER COMMANDS
alias ls='ls --color=auto'
alias ll='ls -lh'
alias la='ll -A'
alias lr='ll -R'
alias l='ll'
alias more='less'
alias grep='grep'
alias df='df -h'
alias du='du -ch'
alias mkdir='mkdir -p -v'
alias nano='nano -w'
alias vi='vim'
alias py='python2.7'
alias uptime='uptime -p'
alias free='free -h'
alias grep='grep --color=always'

alias synctime='sudo ntpd -qg'

alias off='systemctl poweroff'
alias reboot='systemctl reboot'
alias pms='systemctl suspend || /home/jon/bin/lock-script'

alias sup='sudo pacman -Syu'

function fname() { find . -iname "*$@*"; }
function mcd() { mkdir $1 && cd $1; }
function psgrep() { ps axuf | grep -v grep | grep "$@" -i --color=auto; }



complete -cf man
